# Generated by Django 4.2.28 on 2026-04-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobilization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Not Registered', 'Not Registered'), ('Decision Pending', 'Decision Pending')], max_length=20)),
                ('slot', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10, null=True)),
                ('domain', models.CharField(blank=True, choices=[('Digital Marketing', 'Digital Marketing'), ('Logistics and Warehousing', 'Logistics and Warehousing'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Sales and Customer Relation', 'Sales and Customer Relation'), ('ITES', 'ITES')], max_length=100, null=True)),
                ('career_interest', models.TextField(blank=True, null=True)),
                ('aptitude_score', models.IntegerField(blank=True, null=True)),
                ('suitability', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('counselled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mobilization_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.mobilizationrecord')),
            ],
        ),
    ]
