# Generated by Django 4.2.28 on 2026-04-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellinglog',
            name='domain',
            field=models.CharField(blank=True, choices=[('Digital Marketing', 'Digital Marketing'), ('Logistics and Warehousing', 'Logistics and Warehousing'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Sales and Customer Relation', 'Sales and Customer Relation'), ('ITES', 'ITES'), ('Industrial Sewing', 'Industrial Sewing')], max_length=100, null=True),
        ),
    ]
