# Generated by Django 4.2.28 on 2026-04-04 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('caste', models.CharField(max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=14, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(max_length=20)),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('exam_name', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('grade', models.CharField(max_length=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='mobilization.mobilizationrecord')),
            ],
        ),
    ]
