# Generated by Django 4.2.28 on 2026-04-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='age',
        ),
    ]
